### ISSUE TITLE
Can you show some screenshots about your program?

### ISSUE THREAD

**Issue by asmwarrior** [KerryL/LibPlot2D#1]
I suggest put some screenshots of your program in the root markdown file.

**Comment by KerryL** [comment]
Thanks for the suggestion. I added an example to the readme.

**Comment by asmwarrior** [comment]
Hi, thanks for the update.

My suggestion is that you **don't** need to upload the image to the site: https://i.imgur.com/dZ6ks9L.png

You can directly upload the png image file to the github repo, and reference the image(in relative path) in the readme.md file.
